name: Build Unreal Engine Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Visual Studio Build Tools
      uses: microsoft/setup-msbuild@v1.1.0

    - name: Set up Unreal Engine
      run: |
        choco install unrealengine --version=5.4.4 -y
        & 'C:/Program Files/Epic Games/UE_5.4/Engine/Binaries/DotNET/UnrealBuildTool.exe' -projectfiles -project=$(pwd)/Project_Spellcasting/Project_Spellcasting.uproject -game

    - name: Build Unreal Project
      run: |
        & 'C:/Program Files/Epic Games/UE_5.4/Engine/Binaries/DotNET/UnrealBuildTool.exe' Development Win64 -project=$(pwd)/Project_Spellcasting/Project_Spellcasting.uproject -game -progress
